spring:
  profiles:
    active:
      - dev  
---
spring:
  profiles: dev
  gjx: axin3651688
  application:
    name: cnbiconfig-abc-dev
    
---
spring: 
  profiles: default
  application: cnbiconfig-test-default
