mybatis
  name: gjx@cnbisoft.com
  age: 100
spring:
  profiles:
    active:
      - dev  
---
spring:
  profiles: dev
  gjx: luluaxin3651688
  application:
    name: cnbiconfig-abc-dev
    
---
spring: 
  profiles: default
  application: cnbiconfig-test-default
