spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: cnbicloud-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://edmin:cnbisoftjava@eureka-config.com:7301/eureka
info:
  app.name: cnbicloud-dev-1
  company.name: www.cnbisoft.cn
  app.version: v-dev-1.0.0

---
server:
  port: 8102
spring:
  profiles: beta
  application: 
    name: cnbicloud-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://edmin:cnbisoftjava@eureka-config.com:7301/eureka
info:
  app.name: cnbicloud-beta-3
  company.name: www.cnbisoftjava.cn
  app.version: v-beta-3.5.2